export interface CountryCurrency {
  country: string;
  currencyName: string;
  currencyCode: string;
}

export const COUNTRIES_AND_CURRENCIES: CountryCurrency[] = [
  { country: "Afghanistan", currencyName: "Afghan afghani", currencyCode: "AFN" },
  { country: "Akrotiri and Dhekelia (UK)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Aland Islands (Finland)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Albania", currencyName: "Albanian lek", currencyCode: "ALL" },
  { country: "Algeria", currencyName: "Algerian dinar", currencyCode: "DZD" },
  { country: "American Samoa (USA)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Andorra", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Angola", currencyName: "Angolan kwanza", currencyCode: "AOA" },
  { country: "Anguilla (UK)", currencyName: "East Caribbean dollar", currencyCode: "XCD" },
  { country: "Antigua and Barbuda", currencyName: "East Caribbean dollar", currencyCode: "XCD" },
  { country: "Argentina", currencyName: "Argentine peso", currencyCode: "ARS" },
  { country: "Armenia", currencyName: "Armenian dram", currencyCode: "AMD" },
  { country: "Aruba (Netherlands)", currencyName: "Aruban florin", currencyCode: "AWG" },
  { country: "Ascension Island (UK)", currencyName: "Saint Helena pound", currencyCode: "SHP" },
  { country: "Australia", currencyName: "Australian dollar", currencyCode: "AUD" },
  { country: "Austria", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Azerbaijan", currencyName: "Azerbaijan manat", currencyCode: "AZN" },
  { country: "Bahamas", currencyName: "Bahamian dollar", currencyCode: "BSD" },
  { country: "Bahrain", currencyName: "Bahraini dinar", currencyCode: "BHD" },
  { country: "Bangladesh", currencyName: "Bangladeshi taka", currencyCode: "BDT" },
  { country: "Barbados", currencyName: "Barbadian dollar", currencyCode: "BBD" },
  { country: "Belarus", currencyName: "Belarusian ruble", currencyCode: "BYN" },
  { country: "Belgium", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Belize", currencyName: "Belize dollar", currencyCode: "BZD" },
  { country: "Benin", currencyName: "West African CFA franc", currencyCode: "XOF" },
  { country: "Bermuda (UK)", currencyName: "Bermudian dollar", currencyCode: "BMD" },
  { country: "Bhutan", currencyName: "Bhutanese ngultrum", currencyCode: "BTN" },
  { country: "Bolivia", currencyName: "Bolivian boliviano", currencyCode: "BOB" },
  { country: "Bonaire (Netherlands)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Bosnia and Herzegovina", currencyName: "Bosnia and Herzegovina convertible mark", currencyCode: "BAM" },
  { country: "Botswana", currencyName: "Botswana pula", currencyCode: "BWP" },
  { country: "Brazil", currencyName: "Brazilian real", currencyCode: "BRL" },
  { country: "British Indian Ocean Territory (UK)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "British Virgin Islands (UK)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Brunei", currencyName: "Brunei dollar", currencyCode: "BND" },
  { country: "Bulgaria", currencyName: "Bulgarian lev", currencyCode: "BGN" },
  { country: "Burkina Faso", currencyName: "West African CFA franc", currencyCode: "XOF" },
  { country: "Burundi", currencyName: "Burundi franc", currencyCode: "BIF" },
  { country: "Cabo Verde", currencyName: "Cabo Verdean escudo", currencyCode: "CVE" },
  { country: "Cambodia", currencyName: "Cambodian riel", currencyCode: "KHR" },
  { country: "Cameroon", currencyName: "Central African CFA franc", currencyCode: "XAF" },
  { country: "Canada", currencyName: "Canadian dollar", currencyCode: "CAD" },
  { country: "Caribbean Netherlands (Netherlands)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Cayman Islands (UK)", currencyName: "Cayman Islands dollar", currencyCode: "KYD" },
  { country: "Central African Republic", currencyName: "Central African CFA franc", currencyCode: "XAF" },
  { country: "Chad", currencyName: "Central African CFA franc", currencyCode: "XAF" },
  { country: "Chatham Islands (New Zealand)", currencyName: "New Zealand dollar", currencyCode: "NZD" },
  { country: "Chile", currencyName: "Chilean peso", currencyCode: "CLP" },
  { country: "China", currencyName: "Chinese Yuan Renminbi", currencyCode: "CNY" },
  { country: "Christmas Island (Australia)", currencyName: "Australian dollar", currencyCode: "AUD" },
  { country: "Cocos (Keeling) Islands (Australia)", currencyName: "Australian dollar", currencyCode: "AUD" },
  { country: "Colombia", currencyName: "Colombian peso", currencyCode: "COP" },
  { country: "Comoros", currencyName: "Comorian franc", currencyCode: "KMF" },
  { country: "Congo, Democratic Republic of the", currencyName: "Congolese franc", currencyCode: "CDF" },
  { country: "Congo, Republic of the", currencyName: "Central African CFA franc", currencyCode: "XAF" },
  { country: "Cook Islands (New Zealand)", currencyName: "Cook Islands dollar", currencyCode: "NZD" },
  { country: "Costa Rica", currencyName: "Costa Rican colon", currencyCode: "CRC" },
  { country: "Cote d'Ivoire", currencyName: "West African CFA franc", currencyCode: "XOF" },
  { country: "Croatia", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Cuba", currencyName: "Cuban peso", currencyCode: "CUP" },
  { country: "Curacao (Netherlands)", currencyName: "Netherlands Antillean guilder", currencyCode: "ANG" },
  { country: "Cyprus", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Czechia", currencyName: "Czech koruna", currencyCode: "CZK" },
  { country: "Denmark", currencyName: "Danish krone", currencyCode: "DKK" },
  { country: "Djibouti", currencyName: "Djiboutian franc", currencyCode: "DJF" },
  { country: "Dominica", currencyName: "East Caribbean dollar", currencyCode: "XCD" },
  { country: "Dominican Republic", currencyName: "Dominican peso", currencyCode: "DOP" },
  { country: "Ecuador", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Egypt", currencyName: "Egyptian pound", currencyCode: "EGP" },
  { country: "El Salvador", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Equatorial Guinea", currencyName: "Central African CFA franc", currencyCode: "XAF" },
  { country: "Eritrea", currencyName: "Eritrean nakfa", currencyCode: "ERN" },
  { country: "Estonia", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Eswatini", currencyName: "Swazi lilangeni", currencyCode: "SZL" },
  { country: "Ethiopia", currencyName: "Ethiopian birr", currencyCode: "ETB" },
  { country: "Falkland Islands (UK)", currencyName: "Falkland Islands pound", currencyCode: "FKP" },
  { country: "Faroe Islands (Denmark)", currencyName: "Faroese krona", currencyCode: "DKK" },
  { country: "Fiji", currencyName: "Fijian dollar", currencyCode: "FJD" },
  { country: "Finland", currencyName: "European euro", currencyCode: "EUR" },
  { country: "France", currencyName: "European euro", currencyCode: "EUR" },
  { country: "French Guiana (France)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "French Polynesia (France)", currencyName: "CFP franc", currencyCode: "XPF" },
  { country: "Gabon", currencyName: "Central African CFA franc", currencyCode: "XAF" },
  { country: "Gambia", currencyName: "Gambian dalasi", currencyCode: "GMD" },
  { country: "Georgia", currencyName: "Georgian lari", currencyCode: "GEL" },
  { country: "Germany", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Ghana", currencyName: "Ghanaian cedi", currencyCode: "GHS" },
  { country: "Gibraltar (UK)", currencyName: "Gibraltar pound", currencyCode: "GIP" },
  { country: "Greece", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Greenland (Denmark)", currencyName: "Danish krone", currencyCode: "DKK" },
  { country: "Grenada", currencyName: "East Caribbean dollar", currencyCode: "XCD" },
  { country: "Guadeloupe (France)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Guam (USA)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Guatemala", currencyName: "Guatemalan quetzal", currencyCode: "GTQ" },
  { country: "Guernsey (UK)", currencyName: "Guernsey Pound", currencyCode: "GGP" },
  { country: "Guinea", currencyName: "Guinean franc", currencyCode: "GNF" },
  { country: "Guinea-Bissau", currencyName: "West African CFA franc", currencyCode: "XOF" },
  { country: "Guyana", currencyName: "Guyanese dollar", currencyCode: "GYD" },
  { country: "Haiti", currencyName: "Haitian gourde", currencyCode: "HTG" },
  { country: "Honduras", currencyName: "Honduran lempira", currencyCode: "HNL" },
  { country: "Hong Kong (China)", currencyName: "Hong Kong dollar", currencyCode: "HKD" },
  { country: "Hungary", currencyName: "Hungarian forint", currencyCode: "HUF" },
  { country: "Iceland", currencyName: "Icelandic krona", currencyCode: "ISK" },
  { country: "India", currencyName: "Indian rupee", currencyCode: "INR" },
  { country: "Indonesia", currencyName: "Indonesian rupiah", currencyCode: "IDR" },
  { country: "International Monetary Fund (IMF)", currencyName: "SDR (Special Drawing Right)", currencyCode: "XDR" },
  { country: "Iran", currencyName: "Iranian rial", currencyCode: "IRR" },
  { country: "Iraq", currencyName: "Iraqi dinar", currencyCode: "IQD" },
  { country: "Ireland", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Isle of Man (UK)", currencyName: "Manx pound", currencyCode: "IMP" },
  { country: "Israel", currencyName: "Israeli new shekel", currencyCode: "ILS" },
  { country: "Italy", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Jamaica", currencyName: "Jamaican dollar", currencyCode: "JMD" },
  { country: "Japan", currencyName: "Japanese yen", currencyCode: "JPY" },
  { country: "Jersey (UK)", currencyName: "Jersey pound", currencyCode: "JEP" },
  { country: "Jordan", currencyName: "Jordanian dinar", currencyCode: "JOD" },
  { country: "Kazakhstan", currencyName: "Kazakhstani tenge", currencyCode: "KZT" },
  { country: "Kenya", currencyName: "Kenyan shilling", currencyCode: "KES" },
  { country: "Kiribati", currencyName: "Australian dollar", currencyCode: "AUD" },
  { country: "Kosovo", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Kuwait", currencyName: "Kuwaiti dinar", currencyCode: "KWD" },
  { country: "Kyrgyzstan", currencyName: "Kyrgyzstani som", currencyCode: "KGS" },
  { country: "Laos", currencyName: "Lao kip", currencyCode: "LAK" },
  { country: "Latvia", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Lebanon", currencyName: "Lebanese pound", currencyCode: "LBP" },
  { country: "Lesotho", currencyName: "Lesotho loti", currencyCode: "LSL" },
  { country: "Liberia", currencyName: "Liberian dollar", currencyCode: "LRD" },
  { country: "Libya", currencyName: "Libyan dinar", currencyCode: "LYD" },
  { country: "Liechtenstein", currencyName: "Swiss franc", currencyCode: "CHF" },
  { country: "Lithuania", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Luxembourg", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Macau (China)", currencyName: "Macanese pataca", currencyCode: "MOP" },
  { country: "Madagascar", currencyName: "Malagasy ariary", currencyCode: "MGA" },
  { country: "Malawi", currencyName: "Malawian kwacha", currencyCode: "MWK" },
  { country: "Malaysia", currencyName: "Malaysian ringgit", currencyCode: "MYR" },
  { country: "Maldives", currencyName: "Maldivian rufiyaa", currencyCode: "MVR" },
  { country: "Mali", currencyName: "West African CFA franc", currencyCode: "XOF" },
  { country: "Malta", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Marshall Islands", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Martinique (France)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Mauritania", currencyName: "Mauritanian ouguiya", currencyCode: "MRU" },
  { country: "Mauritius", currencyName: "Mauritian rupee", currencyCode: "MUR" },
  { country: "Mayotte (France)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Mexico", currencyName: "Mexican peso", currencyCode: "MXN" },
  { country: "Micronesia", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Moldova", currencyName: "Moldovan leu", currencyCode: "MDL" },
  { country: "Monaco", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Mongolia", currencyName: "Mongolian tugrik", currencyCode: "MNT" },
  { country: "Montenegro", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Montserrat (UK)", currencyName: "East Caribbean dollar", currencyCode: "XCD" },
  { country: "Morocco", currencyName: "Moroccan dirham", currencyCode: "MAD" },
  { country: "Mozambique", currencyName: "Mozambican metical", currencyCode: "MZN" },
  { country: "Myanmar", currencyName: "Myanmar kyat", currencyCode: "MMK" },
  { country: "Namibia", currencyName: "Namibian dollar", currencyCode: "NAD" },
  { country: "Nauru", currencyName: "Australian dollar", currencyCode: "AUD" },
  { country: "Nepal", currencyName: "Nepalese rupee", currencyCode: "NPR" },
  { country: "Netherlands", currencyName: "European euro", currencyCode: "EUR" },
  { country: "New Caledonia (France)", currencyName: "CFP franc", currencyCode: "XPF" },
  { country: "New Zealand", currencyName: "New Zealand dollar", currencyCode: "NZD" },
  { country: "Nicaragua", currencyName: "Nicaraguan cordoba", currencyCode: "NIO" },
  { country: "Niger", currencyName: "West African CFA franc", currencyCode: "XOF" },
  { country: "Nigeria", currencyName: "Nigerian naira", currencyCode: "NGN" },
  { country: "Niue (New Zealand)", currencyName: "New Zealand dollar", currencyCode: "NZD" },
  { country: "Norfolk Island (Australia)", currencyName: "Australian dollar", currencyCode: "AUD" },
  { country: "Northern Mariana Islands (USA)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "North Korea", currencyName: "North Korean won", currencyCode: "KPW" },
  { country: "North Macedonia", currencyName: "Macedonian denar", currencyCode: "MKD" },
  { country: "Norway", currencyName: "Norwegian krone", currencyCode: "NOK" },
  { country: "Oman", currencyName: "Omani rial", currencyCode: "OMR" },
  { country: "Pakistan", currencyName: "Pakistani rupee", currencyCode: "PKR" },
  { country: "Palau", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Palestine", currencyName: "Israeli new shekel", currencyCode: "ILS" },
  { country: "Panama", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Papua New Guinea", currencyName: "Papua New Guinean kina", currencyCode: "PGK" },
  { country: "Paraguay", currencyName: "Paraguayan guarani", currencyCode: "PYG" },
  { country: "Peru", currencyName: "Peruvian sol", currencyCode: "PEN" },
  { country: "Philippines", currencyName: "Philippine peso", currencyCode: "PHP" },
  { country: "Pitcairn Islands (UK)", currencyName: "New Zealand dollar", currencyCode: "NZD" },
  { country: "Poland", currencyName: "Polish zloty", currencyCode: "PLN" },
  { country: "Portugal", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Puerto Rico (USA)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Qatar", currencyName: "Qatari riyal", currencyCode: "QAR" },
  { country: "Reunion (France)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Romania", currencyName: "Romanian leu", currencyCode: "RON" },
  { country: "Russia", currencyName: "Russian ruble", currencyCode: "RUB" },
  { country: "Rwanda", currencyName: "Rwandan franc", currencyCode: "RWF" },
  { country: "Saba (Netherlands)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Saint Barthelemy (France)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Saint Helena (UK)", currencyName: "Saint Helena pound", currencyCode: "SHP" },
  { country: "Saint Kitts and Nevis", currencyName: "East Caribbean dollar", currencyCode: "XCD" },
  { country: "Saint Lucia", currencyName: "East Caribbean dollar", currencyCode: "XCD" },
  { country: "Saint Martin (France)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Saint Pierre and Miquelon (France)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Saint Vincent and the Grenadines", currencyName: "East Caribbean dollar", currencyCode: "XCD" },
  { country: "Samoa", currencyName: "Samoan tala", currencyCode: "WST" },
  { country: "San Marino", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Sao Tome and Principe", currencyName: "Sao Tome and Principe dobra", currencyCode: "STN" },
  { country: "Saudi Arabia", currencyName: "Saudi Arabian riyal", currencyCode: "SAR" },
  { country: "Senegal", currencyName: "West African CFA franc", currencyCode: "XOF" },
  { country: "Serbia", currencyName: "Serbian dinar", currencyCode: "RSD" },
  { country: "Seychelles", currencyName: "Seychellois rupee", currencyCode: "SCR" },
  { country: "Sierra Leone", currencyName: "Sierra Leonean leone", currencyCode: "SLE" },
  { country: "Singapore", currencyName: "Singapore dollar", currencyCode: "SGD" },
  { country: "Sint Eustatius (Netherlands)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Sint Maarten (Netherlands)", currencyName: "Netherlands Antillean guilder", currencyCode: "ANG" },
  { country: "Slovakia", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Slovenia", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Solomon Islands", currencyName: "Solomon Islands dollar", currencyCode: "SBD" },
  { country: "Somalia", currencyName: "Somali shilling", currencyCode: "SOS" },
  { country: "South Africa", currencyName: "South African rand", currencyCode: "ZAR" },
  { country: "South Georgia Island (UK)", currencyName: "Pound sterling", currencyCode: "GBP" },
  { country: "South Korea", currencyName: "South Korean won", currencyCode: "KRW" },
  { country: "South Sudan", currencyName: "South Sudanese pound", currencyCode: "SSP" },
  { country: "Spain", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Sri Lanka", currencyName: "Sri Lankan rupee", currencyCode: "LKR" },
  { country: "Sudan", currencyName: "Sudanese pound", currencyCode: "SDG" },
  { country: "Suriname", currencyName: "Surinamese dollar", currencyCode: "SRD" },
  { country: "Svalbard and Jan Mayen (Norway)", currencyName: "Norwegian krone", currencyCode: "NOK" },
  { country: "Sweden", currencyName: "Swedish krona", currencyCode: "SEK" },
  { country: "Switzerland", currencyName: "Swiss franc", currencyCode: "CHF" },
  { country: "Syria", currencyName: "Syrian pound", currencyCode: "SYP" },
  { country: "Taiwan", currencyName: "New Taiwan dollar", currencyCode: "TWD" },
  { country: "Tajikistan", currencyName: "Tajikistani somoni", currencyCode: "TJS" },
  { country: "Tanzania", currencyName: "Tanzanian shilling", currencyCode: "TZS" },
  { country: "Thailand", currencyName: "Thai baht", currencyCode: "THB" },
  { country: "Timor-Leste", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Togo", currencyName: "West African CFA franc", currencyCode: "XOF" },
  { country: "Tokelau (New Zealand)", currencyName: "New Zealand dollar", currencyCode: "NZD" },
  { country: "Tonga", currencyName: "Tongan pa’anga", currencyCode: "TOP" },
  { country: "Trinidad and Tobago", currencyName: "Trinidad and Tobago dollar", currencyCode: "TTD" },
  { country: "Tristan da Cunha (UK)", currencyName: "Pound sterling", currencyCode: "GBP" },
  { country: "Tunisia", currencyName: "Tunisian dinar", currencyCode: "TND" },
  { country: "Turkey", currencyName: "Turkish lira", currencyCode: "TRY" },
  { country: "Turkmenistan", currencyName: "Turkmen manat", currencyCode: "TMT" },
  { country: "Turks and Caicos Islands (UK)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Tuvalu", currencyName: "Australian dollar", currencyCode: "AUD" },
  { country: "Uganda", currencyName: "Ugandan shilling", currencyCode: "UGX" },
  { country: "Ukraine", currencyName: "Ukrainian hryvnia", currencyCode: "UAH" },
  { country: "United Arab Emirates", currencyName: "UAE dirham", currencyCode: "AED" },
  { country: "United Kingdom", currencyName: "Pound sterling", currencyCode: "GBP" },
  { country: "United States of America", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Uruguay", currencyName: "Uruguayan peso", currencyCode: "UYU" },
  { country: "US Virgin Islands (USA)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Uzbekistan", currencyName: "Uzbekistani som", currencyCode: "UZS" },
  { country: "Vanuatu", currencyName: "Vanuatu vatu", currencyCode: "VUV" },
  { country: "Vatican City (Holy See)", currencyName: "European euro", currencyCode: "EUR" },
  { country: "Venezuela", currencyName: "Venezuelan bolivar", currencyCode: "VES" },
  { country: "Vietnam", currencyName: "Vietnamese dong", currencyCode: "VND" },
  { country: "Wake Island (USA)", currencyName: "United States dollar", currencyCode: "USD" },
  { country: "Wallis and Futuna (France)", currencyName: "CFP franc", currencyCode: "XPF" },
  { country: "Yemen", currencyName: "Yemeni rial", currencyCode: "YER" },
  { country: "Zambia", currencyName: "Zambian kwacha", currencyCode: "ZMW" },
  { country: "Zimbabwe", currencyName: "Zimbabwe gold", currencyCode: "ZWG" },
];

export function getCurrencyForCountry(countryName: string): string {
  const match = COUNTRIES_AND_CURRENCIES.find(c => c.country === countryName);
  return match ? match.currencyCode : 'USD';
}
